name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    name: Lint Backend
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: npm install

      - name: Debug ESLint binary (backend)
        run: |
          ls -l node_modules/.bin/eslint
          file node_modules/.bin/eslint || echo "eslint binary not found"
          ./node_modules/.bin/eslint --version || echo "eslint run failed"

      - name: Run backend lint
        run: npm run lint

  lint-frontend:
    runs-on: ubuntu-latest
    name: Lint Frontend
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm install

      - name: Debug ESLint binary (frontend)
        run: |
          ls -l node_modules/.bin/eslint
          file node_modules/.bin/eslint || echo "eslint binary not found"
          ./node_modules/.bin/eslint --version || echo "eslint run failed"

      - name: Run frontend lint
        run: npm run lint
