name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    name: Lint Backend
    defaults:
      run:
        working-directory: ./ToDo_List/backend
    steps:
      - uses: actions/checkout@v3

      - name: Show backend directory contents
        run: ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: npm install

      - name: Fix permissions for node_modules binaries (backend)
        run: chmod -R +x node_modules/.bin

      - name: Debug ESLint binary (backend)
        run: |
          ls -l node_modules/.bin/eslint
          ./node_modules/.bin/eslint --version

      - name: Run backend lint
        run: npm run lint

  lint-frontend:
    runs-on: ubuntu-latest
    name: Lint Frontend
    defaults:
      run:
        working-directory:  ./ToDo_List/frontend
    steps:
      - uses: actions/checkout@v3

      - name: Show frontend directory contents
        run: ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm install

      - name: Fix permissions for node_modules binaries (frontend)
        run: chmod -R +x node_modules/.bin

      - name: Debug ESLint binary (frontend)
        run: |
          ls -l node_modules/.bin/eslint
          ./node_modules/.bin/eslint --version

      - name: Run frontend lint
        run: npm run lint
